### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by Silviu-Marian** [i18next/i18next-localStorage-cache#2]
Is there a way to clear the cache?

**Comment by jamuhl** [comment]
beside setting expiration - not yet.

but basically just call: `i18next.reloadResources();` will force load even if cache exists and overwrite that with new translations.

else `window.localStorage.removeItem(i18next_res_[lng]);` will do (i18next_res_ is default prefix, and lng is i18next.languages[0])

**Comment by Silviu-Marian** [comment]
Hey, thank you for the quick reply. :)

`localStorage.removeItem()` feels a bit dirty because of `"i18next_res_" + lng`, so `reloadResouces()` seems to be the way to go. I'll get a hash from the server along with the list of languages, and the client can `reloadResources()` if it's out of sync.

It would be great if we could feed those hashes somehow to i18next-localStorage-cache, instead of the `expirationTime` field. 

What do you think? 
I can send you a PR if you like.

**Comment by jamuhl** [comment]
sure if of general use i'm happy to pull in your addition and will publish an update. looking forward to your PR. thanks for contributing.

**Comment by Silviu-Marian** [comment]
Thank you for getting the feature in so quickly :)
I think we can close this one now
