### ISSUE TITLE
react-i18next, { wait: true } and i18next-localStorage-cache don't work

### ISSUE THREAD

**Issue by Silviu-Marian** [i18next/i18next-localStorage-cache#3]
Not sure if this belongs here or in the other project.

There's a `loadNamespaces()` call inside translate.js in react-i18next which doesn't call its callback when the cache has data.

Here's a simple example:

```js

// i18next
const {
  i18next,
  i18nextXHRBackend,
  i18nextLocalStorageCache
} = window

i18next
  .use(i18nextLocalStorageCache)
  .use(i18nextXHRBackend)
  .init({
    nsSeparator: false,
    fallbackLng: false,
    lng: 'en',
    backend: {
      loadPath: './translations/{{lng}}.json'
    },
    cache: {
      enabled: true,
      prefix: 'translations_',
      expirationTime: Infinity
    }
  })

// react-i18next
const {
  I18nextProvider,
  translate
} = window.reactI18next


// Test
const RandomDiv = translate('translation', { wait: true, bindI18n: 'initialized loaded added removed languageChanged' })(() => <p>Hello :)</p>)

// Create Div append to body
const div = document.createElement('div')
document.body.appendChild(div)
ReactDOM.render(<I18nextProvider i18n={i18next}><RandomDiv /></I18nextProvider>, div)

``` 

Thank you :)

**Comment by jamuhl** [comment]
right...will look into a solution asap. thanks for pointing that out.

**Comment by jamuhl** [comment]
took a look at code...not more time available right now (as at work)...will need to create a sample on weekend to reproduce this. not sure where we miss to call the callback...

**Comment by Silviu-Marian** [comment]
No problem. Here is a test repo

https://github.com/Silviu-Marian/i18next-react-cache-wait-3

There's also a sample workaround there 

I hope it helps :)

**Comment by jamuhl** [comment]
found the issue...cache does not callback if no lng is provided -> working on an updating right now

**Comment by jamuhl** [comment]
could you try with: i18next-localstorage-cache@1.0.0

**Comment by Silviu-Marian** [comment]
Wow that was fast 
Looks good to me 

Thank you :)
