### ISSUE TITLE
Cache is disabled by default?

### ISSUE THREAD

**Issue by goloroden** [i18next/i18next-localStorage-cache#6]
If I [get this right](https://github.com/i18next/i18next-localStorage-cache/blob/4c6f9e517e5b4a4862ed2d0f7045b29fa98e2840/src/index.js#L27) the cache is disabled by default. IMHO this is pretty strange and surprising, because if I explicitly `use` the cache, I do not expect that additionally I have to manually enable it.

Is there a special reason why it is like it is, am I missing something, or should this be changed?

**Comment by jamuhl** [comment]
Think i went with this option to let development environment untouched - as caching is contra-productive there - so it "should" just be enabled for production.

**Comment by goloroden** [comment]
Okay, that makes sense - but it comes as a surprise for the user anyway ;-)

Maybe at least the documentation should point this out very clearly?

Oh, and while we are talking about the documentation… mentioning that caching is debounced by 10 seconds would also be helpful. It took me quite a while now to figure out why caching did not work apparently… actually it did, but I never waited long enough ;-)

**Comment by jamuhl** [comment]
added a hint to the docs for enabling in production - only saving is debounced - for obvious reason i think.

**Comment by goloroden** [comment]
Yes, but if it's mentioned *nowhere* it anyway makes you wonder why it apparently doesn't work…

**Comment by jamuhl** [comment]
Doesn't work in your unit test or real life? ;)

**Comment by goloroden** [comment]
I'm just trying things out, and if you use it for the first time, and load a page with caching enabled, have a look at the network tab, reload, and the files are being loaded again, this feels strange.

After a while I realized that sometimes the content is in the local storage, and having a look at the source code then made me see how it actually works.

It's perfectly why to do it like this (actually, it's not a bad idea), but it just gave a bad first experience, because it felt two times (debouncing, and disabled by default) as if things didn't work, and either I am too dumb, or the module is crap.

Apparently, it's neither nor, but the first contact could feel way better ;-).

**Comment by jamuhl** [comment]
Agree it could feel better. If in far future http://locize.com grows enough i'm rather sure i could invest more time in documentation and samples. But currently time is limited :(

**Comment by sapnavyas** [comment]
I am experiencing same the strange issue. with caching enabled, when reload page withing few seconds it loads the files again and after taking pause of say 5 seconds, reload it will not reload until expiry time. I didnt get why it is like this? is there any way to fix this? it should not load file again in subsequent calls regard less of timing.

**Comment by jamuhl** [comment]
The cache get written on every addition to store -> eg. loading multiple files, add resources via resource store API -> to avoid heavy load we debounce writing.

**Comment by sapnavyas** [comment]
is there any way I can minimize debounce timing?

**Comment by jamuhl** [comment]
nope...not currently...you might create a clone or provide a PR to enable that
