### ISSUE TITLE
Feature Request: Customizable debounce wait time

### ISSUE THREAD

**Issue by amermahmud** [i18next/i18next-localStorage-cache#8]
Could we get a way to give a value to the debounce function? Currently, it is set to 10 seconds, which is a bit long. We don't want users to have to redownload the lang files if they are quickly navigating through our site and don't have the lang files cached.

(Also what is the reasoning for the 10 second wait time? Why is it not shorter?)

**Comment by jamuhl** [comment]
the debounce is only there for the cache write - not for read - it's a safety net to not hammer on localstorage write on every change of store.

you users do not have to redownload the language files if navigating -> just set the correct cache headers to your translation files so those get a hit from browser cache on reload.

Anyway...open for a PR to make that configurable.

You might have a look at https://locize.com comes with CDN to load translations from - having the option for setting cache durations on translation file versions.

**Comment by amermahmud** [comment]
Hmm I understand the debounce is only for the cache write, but perhaps our usage of i18next is quite simple (right now), we don't have a 'change of store', we just load the lang files once at page load. 

In any case, I had forgotten that we were going to set the cache headers on the translation files, so in the few cases a user does not wait 10 seconds on the first page with translations, they will retrieve the data from the browser cache, thanks for the reminder :)
