### ISSUE TITLE
cache for React Native

### ISSUE THREAD

**Issue by b-asaf** [i18next/i18next-localStorage-cache#9]
are there any thoughts to fork it for react native as well?

**Comment by jamuhl** [comment]
no...but easy to do: https://www.i18next.com/misc/creating-own-plugins.html#cache

**Comment by jamuhl** [comment]
feel free to create one and share with the community

**Comment by b-asaf** [comment]
my **i18n.js** file looks like thie
```
import en from './en.js';
import de from './de.js';
i18next
    .use(Cache)
    .init({
        ...
        resources: {
            en,
            de,
        },
        cache: {
            enabled: true,
            prefix: '', // my resources files are locally on the same folder as i18n
            expirationTime: Infinity,
        }
    })
```

2 questions:
1. Are `services and options` [here](https://github.com/i18next/i18next-localStorage-cache/blob/master/src/index.js##L35) are take from `cache'
2. am I using the prefix correctly?

where the costume plugin [Cache](https://www.i18next.com/misc/creating-own-plugins.html#cache) is placed? here:

```
cosnt Cache = {
    type: 'cache',
    init: () => {},
    load: () => {
        console.log('i18n costume cache);
    },
}

import en from './en.js';
import de from './de.js';
i18next
    .use(Cache)
    .init({
        ...
        resources: {
            en,
            de,
        },
        cache: {
            enabled: true,
            prefix: '', // my resources files are locally on the same folder as i18n
            expirationTime: Infinity,
        }
    })
```

**Comment by jamuhl** [comment]
you add resources on init...does make zero sense to use some cache -> cache is only useful when loading translations from a backend via xhr, fetch, ...
